language: php
php:
  - 7.4
directories:
  - $HOME/.composer/cache/files
script:
  - composer install --no-interaction --no-autoloader --prefer-dist
  - vendor/bin/phpcs .  --runtime-set ignore_warnings_on_exit 1
